# Generated by Django 4.2.11 on 2026-02-24 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('structure_en', models.CharField(blank=True, max_length=255)),
                ('structure_jp', models.CharField(blank=True, max_length=255)),
                ('structure_kr', models.CharField(blank=True, max_length=255)),
                ('meaning_zh', models.CharField(blank=True, max_length=255)),
                ('answer_en', models.CharField(blank=True, max_length=100)),
                ('answer_jp', models.CharField(blank=True, max_length=100)),
                ('answer_kr', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_zh', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
                ('text_jp', models.TextField(blank=True)),
                ('text_kr', models.TextField(blank=True)),
                ('audio_en_file', models.FileField(blank=True, null=True, upload_to='audio/en/')),
                ('audio_jp_file', models.FileField(blank=True, null=True, upload_to='audio/jp/')),
                ('audio_kr_file', models.FileField(blank=True, null=True, upload_to='audio/kr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='train_engine.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_engine.sentenceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('items', models.ManyToManyField(blank=True, related_name='courses', to='train_engine.sentenceitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserSentenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_level', models.IntegerField(default=1)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_engine.sentenceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_engine.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
