# Generated by Django 4.2.11 on 2026-02-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_engine', '0002_dailycheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='train_engine.course')),
                ('items', models.ManyToManyField(blank=True, to='train_engine.sentenceitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
